version: '3'
services:
  plumber:
    # will build ./docker/plumber
    build: ./docker/plumber
    image: geiser/learning-analytics-camaleon_plumber
    ports:
     - "8080:8080"
    volumes:
     - .:/app
  shiny:
    # will build ./docker/shiny
    build: ./docker/shiny
    image: geiser/learning-analytics-camaleon_shiny
    ports:
      - "3838:3838"
    volumes:
      - 'shiny_logs:/var/log/shiny-server'
      - '.:/srv/shiny-server'

volumes:
  shiny_logs: