version: '3.7'
services:
  plumber:
    build:
      context: ./docker/plumber
      target: ${VERSION}
    image: ${TAG_NAME}:${VERSION}
    container_name: ${APP_NAME}_${VERSION}
    ports:
     - "8080:8080"
    volumes:
     - .:/app
  shiny:
    build:
      context: ./docker/shiny
      target: ${VERSION}
    image: ${TAG_NAME}:${VERSION}
    container_name: ${APP_NAME}_${VERSION}
    ports:
      - "3838:3838"
    volumes:
      - '.:/srv/shiny-server/${APP_NAME}'
      - './shiny_logs:/var/log/shiny-server'
