version: '3.7'
services:
  plumber:
    build:
      context: ./docker/plumber
      target: prod
    image: geiser/learning-analytics-camaleon_plumber
    container_name: learning-analytics-camaleon_plumber
    ports:
     - "8080:8080"
    volumes:
     - .:/app
  shiny:
    build:
      context: ./docker/shiny
      target: prod
    image: geiser/learning-analytics-camaleon_shiny
    container_name: learning-analytics-camaleon_shiny
    ports:
      - "3838:3838"
    volumes:
      - '.:/srv/shiny-server/learning-analytics-camaleon'
      - './shiny_logs:/var/log/shiny-server'
