version: '3'
services:
  plumber:
    build: ./docker/plumber
    image: geiser/learning-analytics-camaleon_plumber:latest
    ports:
     - "8080:8080"
    volumes:
     - .:/app
  shiny:
    build: ./docker/shiny
    image: geiser/learning-analytics-camaleon_shiny:latest
    ports:
      - "3838:3838"
    volumes:
      - '.:/srv/shiny-server'
      - './shiny_logs:/var/log/shiny-server'
